### ISSUE TITLE
Flash memory overflow

### ISSUE THREAD

**Issue by felipengeletrica** [liyanboy74/modbus-stm32-slave-example#1]
Greetings,

           I'm having problems compiling the code it says that the flash memory has run out I just ran "make" and gave the following error:

`ifo.lst fifo/fifo.c -o build/fifo.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F030x6 -DMB_MODE=MB_MODE_SLAVE -ICore/Inc -IDrivers/STM32F0xx_HAL_Driver/Inc -IDrivers/STM32F0xx_HAL_Driver/Inc/Legacy -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Ififo -Imodbus -Os -Wall -fdata-sections -ffunction-sections -g -gdwarf-2 -MMD -MP -MF"build/mb.d" -Wa,-a,-ad,-alms=build/mb.lst modbus/mb.c -o build/mb.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F030x6 -DMB_MODE=MB_MODE_SLAVE -ICore/Inc -IDrivers/STM32F0xx_HAL_Driver/Inc -IDrivers/STM32F0xx_HAL_Driver/Inc/Legacy -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Ififo -Imodbus -Os -Wall -fdata-sections -ffunction-sections -g -gdwarf-2 -MMD -MP -MF"build/mb-check.d" -Wa,-a,-ad,-alms=build/mb-check.lst modbus/mb-check.c -o build/mb-check.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F030x6 -DMB_MODE=MB_MODE_SLAVE -ICore/Inc -IDrivers/STM32F0xx_HAL_Driver/Inc -IDrivers/STM32F0xx_HAL_Driver/Inc/Legacy -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Ififo -Imodbus -Os -Wall -fdata-sections -ffunction-sections -g -gdwarf-2 -MMD -MP -MF"build/mb-crc.d" -Wa,-a,-ad,-alms=build/mb-crc.lst modbus/mb-crc.c -o build/mb-crc.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F030x6 -DMB_MODE=MB_MODE_SLAVE -ICore/Inc -IDrivers/STM32F0xx_HAL_Driver/Inc -IDrivers/STM32F0xx_HAL_Driver/Inc/Legacy -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Ififo -Imodbus -Os -Wall -fdata-sections -ffunction-sections -g -gdwarf-2 -MMD -MP -MF"build/mb-link.d" -Wa,-a,-ad,-alms=build/mb-link.lst modbus/mb-link.c -o build/mb-link.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F030x6 -DMB_MODE=MB_MODE_SLAVE -ICore/Inc -IDrivers/STM32F0xx_HAL_Driver/Inc -IDrivers/STM32F0xx_HAL_Driver/Inc/Legacy -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Ififo -Imodbus -Os -Wall -fdata-sections -ffunction-sections -g -gdwarf-2 -MMD -MP -MF"build/mb-packet.d" -Wa,-a,-ad,-alms=build/mb-packet.lst modbus/mb-packet.c -o build/mb-packet.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F030x6 -DMB_MODE=MB_MODE_SLAVE -ICore/Inc -IDrivers/STM32F0xx_HAL_Driver/Inc -IDrivers/STM32F0xx_HAL_Driver/Inc/Legacy -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Ififo -Imodbus -Os -Wall -fdata-sections -ffunction-sections -g -gdwarf-2 -MMD -MP -MF"build/mb-process.d" -Wa,-a,-ad,-alms=build/mb-process.lst modbus/mb-process.c -o build/mb-process.o
arm-none-eabi-gcc -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F030x6 -DMB_MODE=MB_MODE_SLAVE -ICore/Inc -IDrivers/STM32F0xx_HAL_Driver/Inc -IDrivers/STM32F0xx_HAL_Driver/Inc/Legacy -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Ififo -Imodbus -Os -Wall -fdata-sections -ffunction-sections -g -gdwarf-2 -MMD -MP -MF"build/mb-table.d" -Wa,-a,-ad,-alms=build/mb-table.lst modbus/mb-table.c -o build/mb-table.o
arm-none-eabi-gcc -x assembler-with-cpp -c -mcpu=cortex-m0 -mthumb   -DUSE_HAL_DRIVER -DSTM32F030x6 -DMB_MODE=MB_MODE_SLAVE -ICore/Inc -IDrivers/STM32F0xx_HAL_Driver/Inc -IDrivers/STM32F0xx_HAL_Driver/Inc/Legacy -IDrivers/CMSIS/Device/ST/STM32F0xx/Include -IDrivers/CMSIS/Include -Ififo -Imodbus -Os -Wall -fdata-sections -ffunction-sections -g -gdwarf-2 -MMD -MP -MF"build/startup_stm32f030x6.d" startup_stm32f030x6.s -o build/startup_stm32f030x6.o
arm-none-eabi-gcc build/main.o build/gpio.o build/usart.o build/stm32f0xx_it.o build/stm32f0xx_hal_msp.o build/stm32f0xx_hal_tim.o build/stm32f0xx_hal_tim_ex.o build/stm32f0xx_hal_uart.o build/stm32f0xx_hal_uart_ex.o build/stm32f0xx_hal_rcc.o build/stm32f0xx_hal_rcc_ex.o build/stm32f0xx_hal.o build/stm32f0xx_hal_i2c.o build/stm32f0xx_hal_i2c_ex.o build/stm32f0xx_hal_gpio.o build/stm32f0xx_hal_dma.o build/stm32f0xx_hal_cortex.o build/stm32f0xx_hal_pwr.o build/stm32f0xx_hal_pwr_ex.o build/stm32f0xx_hal_flash.o build/stm32f0xx_hal_flash_ex.o build/stm32f0xx_hal_exti.o build/system_stm32f0xx.o build/tim.o build/fifo.o build/mb.o build/mb-check.o build/mb-crc.o build/mb-link.o build/mb-packet.o build/mb-process.o build/mb-table.o build/startup_stm32f030x6.o -mcpu=cortex-m0 -mthumb   -specs=nano.specs -TSTM32F030F4Px_FLASH.ld  -lc -lm -lnosys  -Wl,-Map=build/MBTest.map,--cref -Wl,--gc-sections -o build/MBTest.elf
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: build/MBTest.elf section `.text' will not fit in region `FLASH'
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: region `FLASH' overflowed by 3296 bytes
collect2: error: ld returned 1 exit status
make: *** [Makefile:185: build/MBTest.elf] Error 1`

**Comment by felipengeletrica** [comment]
I was able to compile but I don't have hardware to test using memory optimization

CFLAGS += -g -gdwarf-2 -Os -flto

**Comment by liyanboy74** [comment]
you have error `will not fit in region` . in this example i use low memory micro stm32f03, 16KB flash and 4KB ram. i think modbus lib need 4KB to run. also i don't show error when run make on windows and it done successfully .

file: [myTerminalOut.txt](https://github.com/ioelectro/modbus-stm32-slave-example/files/11118302/myTerminalOut.txt)
```
   text    data     bss     dec     hex filename
  16000     128    1984   18112    46c0 build/MBTest.elf
```
I try make on linux and get same as your error!
let me fix that ...

**Comment by liyanboy74** [comment]
I want to change micro stm32f03 to stm32f103(blue pill). it's Ok?

**Comment by liyanboy74** [comment]
it's done!

**Comment by liyanboy74** [comment]
It's Done! 
I change code for STM32F103C8T6 (Blue Pill)  for better developing and extend flash size. 
The [old code](https://github.com/ioelectro/modbus-stm32-slave-example/tree/stm32f03) also available

**Comment by liyanboy74** [comment]
Keep in mind that the current project I developed, used a virtual USB COM Port called USB CDC mode. simply u can change code for using hardware UART in physical MODBUS network but just for the simplicity of the project i use USB CDC mode for example.

**Comment by felipengeletrica** [comment]
Greetings,
          Thanks a lot for the reply and the changes. But I would like to use a low-cost microcontroller from STM.
         The bluepill I have to test the new code.

**Comment by liyanboy74** [comment]
I still don't understand the reason for the increase in prog size during compilation on Linux.
